// swift-tools-version:5.9
//
// Distribution package for SDK + Voice + Customization — generated by the Agentforce release
// scripts from each component's scripts/build-xcframework.sh output.
// Wrapper-pattern: each public library product is implemented by a wrapper
// target that carries a binary XCFramework plus its SPM-resolved transitive
// dependencies.
//
// All products ship from the same public SDK repo/release. AgentforceService is
// a shared BINARY dependency and is declared once. AgentforceVoice (when
// present) splices its LiveKitWebRTC / RustLiveKitUniFFI binary targets verbatim
// from the AgentforceVoice build output (single source of truth for their
// versions/checksums). AgentforceCustomization (when present) is a
// binary-on-binary consumer of the AgentforceSDK binary (itself binary-on-binary
// on AgentforceService) plus MobileCustomizationFramework.
//
// Do not hand-edit: regenerated on every SPM release. Dependency lists mirror
// the built dist manifests; a mismatch fails the release (see lib/spm.sh
// verify_combined_manifest_covers_dist).

import PackageDescription

let package = Package(
    name: "AgentforceSDK",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v17)
    ],
    products: [
        .library(
            name: "AgentforceSDK",
            targets: ["AgentforceSDKTarget"]
        ),
        .library(
            name: "AgentforceVoice",
            targets: ["AgentforceVoiceTarget"]
        ),
        .library(
            name: "AgentforceCustomization",
            targets: ["AgentforceCustomizationTarget"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/forcedotcom/SalesforceMobileInterfaces-iOS", from: "1.0.0"),
        .package(url: "https://github.com/Salesforce-Async-Messaging/SMIClientCore-iOS.swift.git", from: "1.11.0"),
        .package(url: "https://github.com/salesforce/SharedUI-iOS", .upToNextMajor(from: "1.3.1")),
        // MobileCustomizationFramework is net-new for AgentforceCustomization.
        // Pinned exact to the version the Customization XCFramework was built
        // against (its binary .swiftinterface verifies against that MCF API).
        .package(url: "https://github.com/salesforce/MobileCustomizationFramework-iOS.git", exact: "6.5.3"),
    ],
    targets: [
        .binaryTarget(
            name: "AgentforceSDK",
            url: "https://github.com/salesforce/AgentforceMobileSDK-iOS/releases/download/19.29.0-rc1/AgentforceMobileSDK-262-3-RC1-spm.xcframework.zip",
            checksum: "6dfb358d8d074eb6eb6b4d338a852958ab7dd84ee1faef441fcf28ae3d62a2c3"
        ),
        .binaryTarget(
            name: "AgentforceVoice",
            url: "https://github.com/salesforce/AgentforceMobileSDK-iOS/releases/download/19.29.0-rc1/AgentforceMobileVoice-262-3-RC1-spm.xcframework.zip",
            checksum: "f88b80c10208356cd72e4b4876fe7fd05e0a0445e75748d99c7b2323eab8037b"
        ),
        .binaryTarget(
            name: "AgentforceService",
            url: "https://github.com/forcedotcom/AgentforceMobileService-iOS/releases/download/6.17.1-rc1/AgentforceMobileService-262-3-RC1-spm.xcframework.zip",
            checksum: "700b48828b341c761a9c1ad6f0d63cdc5ce3075d177ad8ed7b3e5eb0754aacbf"
        ),
        .binaryTarget(
            name: "AgentforceCustomization",
            url: "https://github.com/salesforce/AgentforceMobileSDK-iOS/releases/download/19.29.0-rc1/AgentforceMobileCustomization-262-3-RC1-spm.xcframework.zip",
            checksum: "84211936bb15cb8155094d49f04a25d9af31fa9d7924b49625ac4d5cae94bf1e"
        ),
        .binaryTarget(
            name: "LiveKitWebRTC",
            url: "https://github.com/livekit/webrtc-xcframework/releases/download/137.7151.10/LiveKitWebRTC.xcframework.zip",
            checksum: "fdca78abe7f147bc98f60980245838471688600e0ef178a9463cd09da7fab4c8"
        ),
        .binaryTarget(
            name: "RustLiveKitUniFFI",
            url: "https://github.com/livekit/livekit-uniffi-xcframework/releases/download/0.0.3/RustLiveKitUniFFI.xcframework.zip",
            checksum: "c21c932fc91a44c34f0b6aa896a91fdcbc1e55927974ad15b8cdc5115b95ec3d"
        ),
        .target(
            name: "AgentforceSDKTarget",
            dependencies: [
                "AgentforceSDK",
                "AgentforceService",
                // swift-markdown-ui intentionally omitted (SDK imports it as
                // @_implementationOnly; statically linked into the binary).
                .product(name: "SalesforceLogging",    package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SalesforceNavigation", package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SalesforceNetwork",    package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SalesforceUser",       package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SMIClientCore",        package: "SMIClientCore-iOS.swift"),
                .product(name: "SharedUI", package: "SharedUI-iOS"),
            ],
            path: "Sources/AgentforceSDKTarget"
        ),
        .target(
            name: "AgentforceVoiceTarget",
            dependencies: [
                "AgentforceVoice",
                "AgentforceService",
                "LiveKitWebRTC",
                "RustLiveKitUniFFI",
                // LiveKit itself is @_implementationOnly (statically merged).
                .product(name: "SalesforceNetwork", package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SalesforceLogging", package: "SalesforceMobileInterfaces-iOS"),
                // Surfaced transitively through the AgentforceService binary the
                // Voice XCFramework re-exports; SwiftPM's binary scan warns
                // ("missing a dependency on 'SalesforceUser'/'SalesforceNavigation'")
                // unless the wrapper declares them explicitly.
                .product(name: "SalesforceNavigation", package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SalesforceUser", package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SMIClientCore", package: "SMIClientCore-iOS.swift"),
            ],
            path: "Sources/AgentforceVoiceTarget"
        ),
        .target(
            name: "AgentforceCustomizationTarget",
            dependencies: [
                "AgentforceCustomization",
                // Binary-on-binary: Customization calls AgentforceSDK API through
                // resilient dispatch thunks that only exist because the SDK is a
                // binary (which in turn resolves AgentforceService as a binary).
                "AgentforceSDK",
                "AgentforceService",
                .product(name: "MobileCustomizationFramework", package: "MobileCustomizationFramework-iOS"),
                .product(name: "MobileCustomizationHXL", package: "MobileCustomizationFramework-iOS"),
                .product(name: "SharedUI", package: "SharedUI-iOS"),
                // The AgentforceSDK + MobileCustomizationFramework binary
                // .swiftinterface files import these; declare them so the
                // Customization binary interface verifies. MCF adds SalesforceCache.
                .product(name: "SalesforceLogging",    package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SalesforceNavigation", package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SalesforceNetwork",    package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SalesforceUser",       package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SalesforceCache",      package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SMIClientCore",        package: "SMIClientCore-iOS.swift"),
            ],
            path: "Sources/AgentforceCustomizationTarget"
        ),
    ]
)
