// swift-tools-version:5.9
//
// Distribution package for SDK + Voice — generated by the Agentforce release
// scripts from each component's scripts/build-xcframework.sh output.
// Wrapper-pattern: each public library product is implemented by a wrapper
// target that carries a binary XCFramework plus its SPM-resolved transitive
// dependencies.
//
// All products ship from the same public SDK repo/release. AgentforceService is
// a shared BINARY dependency and is declared once. AgentforceVoice (when
// present) splices its LiveKitWebRTC / RustLiveKitUniFFI binary targets verbatim
// from the AgentforceVoice build output (single source of truth for their
// versions/checksums). AgentforceCustomization (when present) is a
// binary-on-binary consumer of the AgentforceSDK binary (itself binary-on-binary
// on AgentforceService) plus MobileCustomizationFramework.
//
// Do not hand-edit: regenerated on every SPM release. Dependency lists mirror
// the built dist manifests; a mismatch fails the release (see lib/spm.sh
// verify_combined_manifest_covers_dist).

import PackageDescription

let package = Package(
    name: "AgentforceSDK",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v17)
    ],
    products: [
        .library(
            name: "AgentforceSDK",
            targets: ["AgentforceSDKTarget"]
        ),
        .library(
            name: "AgentforceVoice",
            targets: ["AgentforceVoiceTarget"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/forcedotcom/SalesforceMobileInterfaces-iOS", from: "1.0.0"),
        .package(url: "https://github.com/Salesforce-Async-Messaging/SMIClientCore-iOS.swift.git", from: "1.11.0"),
        .package(url: "https://github.com/salesforce/SharedUI-iOS", .upToNextMajor(from: "1.3.1")),
    ],
    targets: [
        .binaryTarget(
            name: "AgentforceSDK",
            url: "https://github.com/salesforce/AgentforceMobileSDK-iOS/releases/download/18.26.23/AgentforceMobileSDK-262-1-4-spm.xcframework.zip",
            checksum: "69c93b107b73b15e635a3cce920a02783f86f405cf79a16e700bf964d0722ad6"
        ),
        .binaryTarget(
            name: "AgentforceVoice",
            url: "https://github.com/salesforce/AgentforceMobileSDK-iOS/releases/download/18.26.23/AgentforceMobileVoice-262-1-4-spm.xcframework.zip",
            checksum: "95525597e8cd88df94bec54880912b61d63f495aca560463d94cfdd026c9c067"
        ),
        .binaryTarget(
            name: "AgentforceService",
            url: "https://github.com/forcedotcom/AgentforceMobileService-iOS/releases/download/6.11.6/AgentforceMobileService-262-1-4-spm.xcframework.zip",
            checksum: "1bbf87c01c9b185004e82e1014b6009a2d51a005d1931c68e3c6d7150472ac7e"
        ),
        .binaryTarget(
            name: "LiveKitWebRTC",
            url: "https://github.com/livekit/webrtc-xcframework/releases/download/137.7151.10/LiveKitWebRTC.xcframework.zip",
            checksum: "fdca78abe7f147bc98f60980245838471688600e0ef178a9463cd09da7fab4c8"
        ),
        .binaryTarget(
            name: "RustLiveKitUniFFI",
            url: "https://github.com/livekit/livekit-uniffi-xcframework/releases/download/0.0.3/RustLiveKitUniFFI.xcframework.zip",
            checksum: "c21c932fc91a44c34f0b6aa896a91fdcbc1e55927974ad15b8cdc5115b95ec3d"
        ),
        .target(
            name: "AgentforceSDKTarget",
            dependencies: [
                "AgentforceSDK",
                "AgentforceService",
                // swift-markdown-ui intentionally omitted (SDK imports it as
                // @_implementationOnly; statically linked into the binary).
                .product(name: "SalesforceLogging",    package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SalesforceNavigation", package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SalesforceNetwork",    package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SalesforceUser",       package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SMIClientCore",        package: "SMIClientCore-iOS.swift"),
                .product(name: "SharedUI", package: "SharedUI-iOS"),
            ],
            path: "Sources/AgentforceSDKTarget"
        ),
        .target(
            name: "AgentforceVoiceTarget",
            dependencies: [
                "AgentforceVoice",
                "AgentforceService",
                "LiveKitWebRTC",
                "RustLiveKitUniFFI",
                // LiveKit itself is @_implementationOnly (statically merged).
                .product(name: "SalesforceNetwork", package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SalesforceLogging", package: "SalesforceMobileInterfaces-iOS"),
                // Surfaced transitively through the AgentforceService binary the
                // Voice XCFramework re-exports; SwiftPM's binary scan warns
                // ("missing a dependency on 'SalesforceUser'/'SalesforceNavigation'")
                // unless the wrapper declares them explicitly.
                .product(name: "SalesforceNavigation", package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SalesforceUser", package: "SalesforceMobileInterfaces-iOS"),
                .product(name: "SMIClientCore", package: "SMIClientCore-iOS.swift"),
            ],
            path: "Sources/AgentforceVoiceTarget"
        ),
    ]
)
